name: Regular Action
run-name: ${{ github.actor }} is learning GitHub Actions
env:
  globalVar: "a global variable value"

on:
  push:
  workflow_dispatch:

jobs:
  jobNamedByMe:
    runs-on: ubuntu-latest
    env:
      myJobVar: Hello from job var
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        env:
          step1Var: "hi from step var"
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Global var value=$globalVar"
          echo "Job var value=$myJobVar"
          echo "Step var value=$step1Var"
          
      - name: Check custom env variables
        run: |
          echo "Custom variable (missing)=$myVar"
          echo "Global var value=$globalVar"
          echo "Job var value=$myJobVar"
          echo "Previous Step var value=$step1Var"
  jobNo2:
    runs-on: ubuntu-latest
    env:
      myJob2Var: Hi from Job #2
    steps:
      - name: Step 1 in Job2
        env:
          step2Var: "Hi from Step1, Job2"
        run: |
          echo Checking env variables.
          echo "Global var value=$globalVar"
          echo "Job 1 var value=$myJobVar"
          echo "Job 2 var value=$myJob2Var"
          echo "Step 2 var value=$step2Var"
          echo "Step 1 Job 1 var value=$step1Var"
      - name: Check Job Defaults
        run: echo "Default values=${{ jobs.jobNo2.defaults}}"
