name: Action using reusable
run-name: ${{ github.actor }} is running twice a reusable action

on:
  push:
  workflow_dispatch:

jobs:
  jobNo1:
    uses: volvas/dry-in-gha/.github/workflows/reusable.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}

  jobNo2:
    uses: volvas/dry-in-gha/.github/workflows/reusable.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
