name: Reusable Action
run-name: ${{ github.actor }} is running reusable action

on:
  workflow_call:
    inputs:
      input-arg:
        required: true
        type: string

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check passed argument
        env:
          inputArg: ${{ inputs.input-arg }}
        run: echo "Got input=$inputArg"
