name: Uses local action

on:
  workflow_dispatch:

jobs:
  test-local-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Call local action
        id: random-generator
        uses: ./.github/actions/my-action
        with:
          any-input: custom value

      - name: Print random
        env:
          RANDOM_NO: ${{ steps.random-generator.outputs.random-number }}
        run: echo "Got random=$RANDOM_NO"
